# Generated by Django 3.1.5 on 2021-02-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank='False', max_length=200)),
                ('detail', models.TextField(blank='False')),
                ('img', models.ImageField(blank='True', upload_to='')),
            ],
        ),
    ]
